### ISSUE TITLE
Move it to Flowbite organisation

### ISSUE THREAD

**Issue by zoltanszogyenyi** [themesberg/flowbite-blazor-legacy#42]
Hey @tdashworth,

I'm glad to see a repo with an integration of Flowbite with Blazor.

Do you think we could move this to the official Flowbite organisation and see if it gains enough traction to get more contributors to contribute?

Let me know.

Cheers,
Zoltan

**Comment by tdashworth** [comment]
Hey @zoltanszogyenyi, I have just tried, but I don't have permission in the `themesberg` organisation. Could you help with that?

Tom

**Comment by zoltanszogyenyi** [comment]
Hey @tdashworth,

Can you invite me as an administrator to this repository and then I'll transfer it over - after that I'll invite you back there.

Cheers,
Zoltan

**Comment by zoltanszogyenyi** [comment]
Hey @tdashworth,

I got the invitation - but I can't see the project settings tab.

Can we DM each other via Twitter? Should be easier to figure it out.

My account: https://twitter.com/zoltanszogyenyi

Cheers,
Zoltan
