### ISSUE TITLE
Scam Website in readme.md

### ISSUE THREAD

**Issue by ruohki** [themesberg/flowbite-blazor-legacy#43]
One of your links in your readme.md redirects to a scam website [https://flowbite-blazor.com/](https://flowbite-blazor.com/)

**Comment by wdcossey** [comment]
None of the links work in the readme.md, they all redirect to some [dodgy] url (http://ww17.flowbite-blazor.com/).

Either the domain registration has lapsed or has been hijacked.

Can you please update the readme.md with working urls (or remove the urls entirely)?

**Comment by tdashworth** [comment]
Links have been updated to `#` so that they don't go anywhere. This project doesn't have a site yet. 

Apologies for any confusion this has caused.
