### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by stefandevo** [themesberg/flowbite-blazor-legacy#46]
This repo is referenced from the official flow bite site, but it seems there is nothing here (yet).
I see 1 PR for the Alert component, but even that is not merged.

Open question: any idea if this repo is active?

**Comment by zoltanszogyenyi** [comment]
Hello @stefandevo,

Thanks for writing! We are currently looking for a maintainer for Flowbite Blazor :)

Cheers,
Zoltan
